name: AWS Kotlin SDK CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        directory: [ upload-s3-file/ ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{matrix.directory}}

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ${{matrix.directory}}
